export default {
  settings_page: {
    settings_title: 'Settings',
    icloud_name: 'Sicmatr1x.E.G',
    icloud_hint: 'Apple ID, iCloud, iTunes & App Store',
    basic_setting_block: {
      airplane_mode: 'Airplane Mode',
      wifi: 'Wi-Fi',
      Bluetooth: 'Bluetooth',
      Cellular: 'Cellular',
      personal_hotspot: 'Personal Hotspot',
      vpn: 'VPN',
      notifications: 'Notifications',
      sounds_haptics: 'Sounds & Haptics',
      do_not_disturb: 'Do Not Disturb',
      screen_time: 'Screen Time',
      general: 'General',
      control_center: 'Control Center',
      display_brightness: 'Display & Brightness',
      wallpaper: 'Wallpaper',
      siri_search: 'Siri & Search',
      touch_id_passcode: 'Touch ID & Passcode',
      emergency_sos: 'Emergency SOS',
      battery: 'Battery',
      privacy: 'Privacy',
      itunes_app_store: 'iTunes & App Store',
      wallet_apple_pay: 'Wallet & Apple Pay',
      password_accounts: 'Password & Accounts',
      mail: 'Mail',
      contacts: 'Contacts',
      calendar: 'Calendar',
      notes: 'Notes',
      reminders: 'Reminders',
      voice_memos: 'Voice Memos',
      phone: 'Phone',
      messages: 'Messages',
      facetime: 'FaceTime',
      maps: 'Maps',
      measure: 'Measure',
      safari: 'Safari',
      news: 'News',
      music: 'Music',
      videos: 'Videos',
      photos: 'Photos',
      camera: 'Camera',
      podcasts: 'Podcasts',
      game_center: 'Game Center',
      developer: 'Developer',
    }
  },
  wifi_page: {
    title: 'Wi-Fi',
    sub_title: 'Wi-Fi',
    wifi_hint: 'New WiFi- network connections have been turned off from Control Center.',
    choose_a_network: 'CHOOSE A NETWORK...',
    other: 'Other...',
    ask_to_join_network: 'Ask to Join Networks',
    hint: 'Known networks will be joined automatically. If no known networks are available, you will be asked before joining a new network.'
  }
}